name: codechecker-build
channels:
  - conda-forge

dependencies:
  - python
  - mkdocs==1.2.3
  - lxml==4.7.1
  - sqlalchemy==1.3.23
  - alembic==1.5.5
  - portalocker==2.2.1
  - psutil==5.8.0
  - mypy_extensions==0.4.3
  - thrift==0.13.0
  - gitpython==3.1.11
  - PyYAML==5.4.1
  - pip
  - setuptools
  - conda-build
  - virtualenv