package:
  name: codechecker
  version: 6.21.0

source:
  path: ./
   
requirements:
  build:
    - python==3.9.15
    - setuptools==65.6.3
    - lxml==4.7.1
    - portalocker==2.2.1
    - psutil==5.8.0
    - PyYAML==5.4.1
    - mypy_extensions==0.4.3
    - sqlalchemy==1.3.23
    - alembic==1.5.5
    - thrift==0.13.0
    - gitpython==3.1.11
    - conda-build==3.23.1

  run:
    - python
    - portalocker==2.2.1
    - psutil==5.8.0
    - PyYAML==5.4.1
    - sqlalchemy==1.3.23
    - thrift==0.13.0
    - mypy_extensions
    - lxml==4.7.1
    - alembic==1.5.5
    - gitpython==3.1.11    

test:
  imports:
    - codechecker_report_converter
    - codechecker_merge_clang_extdef_mappings
    - tu_collector

about:
  home: